/**
 * Styles bundled with the module, seeded into a world the first time Illuminus
 * runs there.
 *
 * There are none at the moment: the sample styles that will ship with the
 * module are being made, along with the artwork they use. A world therefore
 * starts with no styles at all, which is a fair first impression — the library
 * says how to make one, and nothing is pretending to be finished.
 *
 * When they arrive, each preset lists only the values that differ from the
 * schema defaults, and is generated by running the previous schema version's
 * data through `scripts/migrations.mjs` rather than hand-written — which
 * exercises the migration on real data at the same time.
 */

export const PRESETS = [];
